kumuluzee:
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                  <Configuration name="gotax_log">
                      <Appenders>
                          <Console name="console" target="SYSTEM_OUT">
                              <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                          </Console>
                      </Appenders>
                      <Loggers>
                          <Root level="DEBUG">
                              <AppenderRef ref="console"/>
                          </Root>
                                     <logger name="org.bizzdeskgroup.Dtos.Query.UserDto" additivity="false"> <!-- <==== define the log level for your own mapper -->
                                         <level value="DEBUG"/>
                                     <appender-ref ref="console"/>
                                     <logger name="org.bizzdeskgroup.models.User" additivity="false"> <!-- <==== define the log level for your own mapper -->
                                         <level value="DEBUG"/>
                                         <appender-ref ref="console"/>
                                 </logger>
                      </Loggers>
                  </Configuration>'